services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - db
  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_USER=spaced
      - POSTGRES_PASSWORD=spaced
      - POSTGRES_DB=spaced
  s3:
    image: localstack/localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
