services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - db
  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_USER=spaced
      - POSTGRES_PASSWORD=spaced
      - POSTGRES_DB=spaced